name: deploy snapshot

on:
  push:
    branches:
      - develop

jobs:
  deploy-snapshot:

    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: SetOutput
        run: |
          chmod +x ci/output.sh
          ci/output.sh
      - name: PrintOutput
        env:
          TAG: ${{ steps.SetOutput.outputs.latest_tag }}
        run: |
          chmod +x ci/showoutput.sh
          ci/showoutput.sh  
      # Run maven verify
      - name: Maven verify
        run: mvn verify --batch-mode
      # Run maven deploy
      - name: Maven deploy
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Username: $USERNAME"
          echo "Password: $PASSWORD"
          chmod +x ci/print.sh
          ci/print.sh
